# Name of your workflow
name: CI/CD Docker Pipeline

# 1. Trigger: When does this workflow run?
on:
  push:
    branches: [ "main" ] # Runs on pushes to the main branch
  workflow_dispatch: # Allows manual triggering from the Actions tab

# 2. Jobs: What tasks should be performed?
jobs:
  build-and-push:
    # 3. Runner: What machine will this run on?
    runs-on: ubuntu-latest

    # 4. Steps: The sequence of actions to perform
    steps:
      # Checks out your repository's code so the job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Logs into Docker Hub using the secrets you stored
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # This is the main action that builds the Docker image from your Dockerfile
      # and pushes it to your Docker Hub repository
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:latest